<html lang="ja"><head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>月給計算機</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 20px;
            background-color: #f9f9f9;
            color: #333;
        }
        .container {
            max-width: 600px;
            margin: 0 auto;
            background: #fff;
            padding: 20px;
            border-radius: 8px;
            box-shadow: 0 2px 10px rgba(0, 0, 0, 0.1);
        }
        h1 {
            text-align: center;
            color: #4CAF50;
        }
        .controls {
            margin-bottom: 20px;
        }
        label {
            display: block;
            margin: 10px 0 5px;
            font-weight: bold;
        }
        input[type="number"], select, button {
            width: 100%;
            padding: 10px;
            margin: 5px 0 10px;
            box-sizing: border-box;
            border: 1px solid #ddd;
            border-radius: 4px;
            font-size: 16px;
        }
        button {
            background-color: #4CAF50;
            color: #fff;
            cursor: pointer;
        }
        button:hover {
            background-color: #45a049;
        }
        .result {
            text-align: center;
            font-size: 18px;
            font-weight: bold;
        }
        .calendar-container {
            display: none;
            text-align: center;
        }
        .calendar {
            display: grid;
            grid-template-columns: repeat(7, 1fr);
            gap: 2px;
            max-width: 100%;
        }
        .calendar div {
            border: 1px solid #ddd;
            padding: 10px;
            box-sizing: border-box;
            position: relative;
        }
        .calendar .header {
            font-weight: bold;
            text-align: center;
        }
        .calendar .header.sun {
            background-color: #FFCCCB; /* 日曜日の背景色 */
        }
        .calendar .header.sat {
            background-color: #ADD8E6; /* 土曜日の背景色 */
        }
        .calendar .header {
            background-color: #f0f0f0; /* 他の曜日の背景色 */
        }
        .calendar .day {
            cursor: pointer;
            position: relative;
        }
        .calendar .day:hover {
            background-color: #f0f0f0;
        }
        .hours-input {
            position: absolute;
            bottom: 0;
            background: rgba(255, 0, 0, 0.1); /* 薄い赤色 */
            border-top: 1px solid #ddd;
            width: 100%;
            text-align: center;
            font-size: 12px;
            padding: 2px;
            box-sizing: border-box;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>月給計算機</h1>
        
        <div class="controls">
            <label for="hourlyWage">時給（円）:</label>
            <input type="number" id="hourlyWage" placeholder="時給を入力" min="0">

            <label for="workHours">働いた時間を選択:</label>
            <select id="workHours">
                <!-- 1〜24時間の選択肢 -->
                <option value="1">1時間</option>
                <option value="2">2時間</option>
                <option value="3">3時間</option>
                <option value="4">4時間</option>
                <option value="5">5時間</option>
                <option value="6">6時間</option>
                <option value="7">7時間</option>
                <option value="8">8時間</option>
                <option value="9">9時間</option>
                <option value="10">10時間</option>
                <option value="11">11時間</option>
                <option value="12">12時間</option>
                <option value="13">13時間</option>
                <option value="14">14時間</option>
                <option value="15">15時間</option>
                <option value="16">16時間</option>
                <option value="17">17時間</option>
                <option value="18">18時間</option>
                <option value="19">19時間</option>
                <option value="20">20時間</option>
                <option value="21">21時間</option>
                <option value="22">22時間</option>
                <option value="23">23時間</option>
                <option value="24">24時間</option>
                <!-- 0.5〜23.5時間の選択肢 -->
                <option value="0.5">0.5時間</option>
                <option value="1.5">1.5時間</option>
                <option value="2.5">2.5時間</option>
                <option value="3.5">3.5時間</option>
                <option value="4.5">4.5時間</option>
                <option value="5.5">5.5時間</option>
                <option value="6.5">6.5時間</option>
                <option value="7.5">7.5時間</option>
                <option value="8.5">8.5時間</option>
                <option value="9.5">9.5時間</option>
                <option value="10.5">10.5時間</option>
                <option value="11.5">11.5時間</option>
                <option value="12.5">12.5時間</option>
                <option value="13.5">13.5時間</option>
                <option value="14.5">14.5時間</option>
                <option value="15.5">15.5時間</option>
                <option value="16.5">16.5時間</option>
                <option value="17.5">17.5時間</option>
                <option value="18.5">18.5時間</option>
                <option value="19.5">19.5時間</option>
                <option value="20.5">20.5時間</option>
                <option value="21.5">21.5時間</option>
                <option value="22.5">22.5時間</option>
                <option value="23.5">23.5時間</option>
            </select>

            <button onclick="calculateSalary()">計算する</button>
            <button onclick="toggleCalendar()">カレンダー表示</button>
        </div>

        <div id="calendar" class="calendar-container">
            <div class="calendar">
                <div class="header sun">日</div>
                <div class="header">月</div>
                <div class="header">火</div>
                <div class="header">水</div>
                <div class="header">木</div>
                <div class="header">金</div>
                <div class="header sat">土</div>

                <!-- 8月のカレンダーの手書き風表示 -->
                <!-- 曜日の位置に合わせて日付を配置 -->
                <!-- 1日: 木曜日 -->
                <div class="day sun" onclick="selectDay(this)">1</div>
                <div class="day" onclick="selectDay(this)">2</div>
                <div class="day" onclick="selectDay(this)">3</div>
                <div class="day" onclick="selectDay(this)">4</div>
                <div class="day" onclick="selectDay(this)">5</div>
                <div class="day" onclick="selectDay(this)">6</div>
                <div class="day sat" onclick="selectDay(this)">7</div>
                <div class="day sun" onclick="selectDay(this)">8</div>
                <div class="day" onclick="selectDay(this)">9</div>
                <div class="day" onclick="selectDay(this)">10</div>
                <div class="day" onclick="selectDay(this)">11</div>
                <div class="day" onclick="selectDay(this)">12</div>
                <div class="day" onclick="selectDay(this)">13</div>
                <div class="day sat" onclick="selectDay(this)">14</div>
                <div class="day sun" onclick="selectDay(this)">15</div>
                <div class="day" onclick="selectDay(this)">16</div>
                <div class="day" onclick="selectDay(this)">17</div>
                <div class="day" onclick="selectDay(this)">18</div>
                <div class="day" onclick="selectDay(this)">19</div>
                <div class="day" onclick="selectDay(this)">20</div>
                <div class="day sat" onclick="selectDay(this)">21</div>
                <div class="day sun" onclick="selectDay(this)">22</div>
                <div class="day" onclick="selectDay(this)">23</div>
                <div class="day" onclick="selectDay(this)">24</div>
                <div class="day" onclick="selectDay(this)">25</div>
                <div class="day" onclick="selectDay(this)">26</div>
                <div class="day" onclick="selectDay(this)">27</div>
                <div class="day sat" onclick="selectDay(this)">28</div>
                <div class="day sun" onclick="selectDay(this)">29</div>
                <div class="day" onclick="selectDay(this)">30</div>
                <div class="day" onclick="selectDay(this)">31</div>
            </div>
        </div>

        <div class="result" id="result"></div>
    </div>

    <script>
        let calendarVisible = false;
        let totalWorkHours = 0;

        function calculateSalary() {
            const hourlyWage = parseFloat(document.getElementById("hourlyWage").value);

            if (!hourlyWage || totalWorkHours === 0) {
                alert("時給と働いた時間を正しく入力してください。");
                return;
            }

            const salary = hourlyWage * totalWorkHours;
            document.getElementById("result").innerText = `月給: ${salary.toLocaleString()}円`;
        }

        function toggleCalendar() {
            calendarVisible = !calendarVisible;
            document.getElementById("calendar").style.display = calendarVisible ? 'block' : 'none';
        }

        function selectDay(element) {
            const workHoursSelect = document.getElementById("workHours");
            const workHours = parseFloat(workHoursSelect.value);

            if (element.querySelector('.hours-input')) {
                // 既に選択された時間がある場合はその時間を減算して取り消し
                totalWorkHours -= parseFloat(element.querySelector('.hours-input').innerText);
                element.querySelector('.hours-input').remove();
                element.style.backgroundColor = ""; // 背景色を元に戻す
            } else {
                // 選択されていない場合はその時間を加算
                totalWorkHours += workHours;
                const hoursInput = document.createElement("div");
                hoursInput.classList.add("hours-input");
                hoursInput.innerText = workHours + "時間"; // 単位を追加
                element.appendChild(hoursInput);
                element.style.backgroundColor = "#ffeb3b"; // 背景色を選択された色に変更
            }
        }
    </script>

</body></html>
